import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const sampleScouts = [
  {
    scout_name: 'Carlos Rodriguez',
    name: 'Carlos',
    surname: 'Rodriguez',
    date_of_birth: new Date('1988-03-15'),
    age: 35,
    nationality: 'Spain',
    email: 'carlos.rodriguez@scoutnetwork.com',
    phone: '+34 612 345 678',
    city: 'Madrid',
    country: 'Spain',
    favourite_club: 'Real Madrid',
    open_to_work: true,
    professional_experience: 'Former Real Madrid youth scout with 12 years of experience',
    nationality_expertise: 'Spain',
    competition_expertise: 'La Liga',
    total_reports: 45,
    total_reports_norm: 0.85,
    total_reports_rank: 15,
    original_reports: 38,
    original_reports_norm: 0.82,
    original_reports_rank: 12,
    avg_potential: 7.8,
    avg_initial_age: 18.5,
    total_investment: 15000000,
    total_investment_rank: 8,
    net_profits: 8500000,
    net_profits_rank: 6,
    roi: 15.5,
    roi_norm: 0.78,
    roi_rank: 10,
    max_profit_report: 2500000,
    max_profit_report_rank: 5,
    min_profit_report: -150000,
    avg_profit_report: 188888,
    avg_profit_report_norm: 0.75,
    avg_profit_report_rank: 8,
    transfer_team_pts: 85.5,
    transfer_team_pts_norm: 0.82,
    transfer_team_pts_rank: 12,
    avg_initial_team_elo: 1650,
    avg_initial_team_level: 'Good',
    transfer_competition_pts: 92.3,
    transfer_competition_pts_norm: 0.88,
    transfer_competition_pts_rank: 7,
    avg_initial_competition_elo: 1750,
    avg_initial_competition_level: 'Very Good',
    scout_elo: 2150,
    scout_level: 'Elite',
    scout_ranking: 8,
    join_date: new Date('2020-01-15')
  },
  {
    scout_name: 'Maria Silva',
    name: 'Maria',
    surname: 'Silva',
    date_of_birth: new Date('1994-07-22'),
    age: 29,
    nationality: 'Brazil',
    email: 'maria.silva@scoutbrasil.com',
    phone: '+55 11 98765-4321',
    city: 'São Paulo',
    country: 'Brazil',
    favourite_club: 'Santos FC',
    open_to_work: true,
    professional_experience: 'Specialized in South American talent identification',
    nationality_expertise: 'Brazil',
    competition_expertise: 'Brazilian Serie A',
    total_reports: 32,
    total_reports_norm: 0.72,
    total_reports_rank: 25,
    original_reports: 28,
    original_reports_norm: 0.75,
    original_reports_rank: 22,
    avg_potential: 8.2,
    avg_initial_age: 17.8,
    total_investment: 8500000,
    total_investment_rank: 18,
    net_profits: 4200000,
    net_profits_rank: 15,
    roi: 12.3,
    roi_norm: 0.65,
    roi_rank: 18,
    max_profit_report: 1800000,
    max_profit_report_rank: 12,
    min_profit_report: -80000,
    avg_profit_report: 131250,
    avg_profit_report_norm: 0.68,
    avg_profit_report_rank: 16,
    transfer_team_pts: 78.2,
    transfer_team_pts_norm: 0.75,
    transfer_team_pts_rank: 20,
    avg_initial_team_elo: 1580,
    avg_initial_team_level: 'Average',
    transfer_competition_pts: 88.7,
    transfer_competition_pts_norm: 0.85,
    transfer_competition_pts_rank: 10,
    avg_initial_competition_elo: 1680,
    avg_initial_competition_level: 'Good',
    scout_elo: 1980,
    scout_level: 'Excellent',
    scout_ranking: 15,
    join_date: new Date('2021-03-10')
  },
  {
    scout_name: 'Jean Dubois',
    name: 'Jean',
    surname: 'Dubois',
    date_of_birth: new Date('1981-11-08'),
    age: 42,
    nationality: 'France',
    email: 'jean.dubois@scoutfrance.fr',
    phone: '+33 6 12 34 56 78',
    city: 'Lyon',
    country: 'France',
    favourite_club: 'Olympique Lyonnais',
    open_to_work: false,
    professional_experience: 'Senior scout with extensive European network',
    nationality_expertise: 'France',
    competition_expertise: 'Ligue 1',
    total_reports: 67,
    total_reports_norm: 0.95,
    total_reports_rank: 3,
    original_reports: 58,
    original_reports_norm: 0.92,
    original_reports_rank: 4,
    avg_potential: 7.5,
    avg_initial_age: 19.2,
    total_investment: 22000000,
    total_investment_rank: 2,
    net_profits: 12800000,
    net_profits_rank: 3,
    roi: 18.7,
    roi_norm: 0.88,
    roi_rank: 4,
    max_profit_report: 3200000,
    max_profit_report_rank: 2,
    min_profit_report: -200000,
    avg_profit_report: 191044,
    avg_profit_report_norm: 0.82,
    avg_profit_report_rank: 5,
    transfer_team_pts: 91.8,
    transfer_team_pts_norm: 0.88,
    transfer_team_pts_rank: 6,
    avg_initial_team_elo: 1720,
    avg_initial_team_level: 'Very Good',
    transfer_competition_pts: 95.1,
    transfer_competition_pts_norm: 0.91,
    transfer_competition_pts_rank: 4,
    avg_initial_competition_elo: 1820,
    avg_initial_competition_level: 'Excellent',
    scout_elo: 1750,
    scout_level: 'Very Good',
    scout_ranking: 25,
    join_date: new Date('2019-08-20')
  },
  {
    scout_name: 'Alessandro Rossi',
    name: 'Alessandro',
    surname: 'Rossi',
    date_of_birth: new Date('1985-05-12'),
    age: 38,
    nationality: 'Italy',
    email: 'alessandro.rossi@scoutitalia.it',
    phone: '+39 335 123 4567',
    city: 'Milan',
    country: 'Italy',
    favourite_club: 'AC Milan',
    open_to_work: true,
    professional_experience: 'Former AC Milan academy scout, Serie A specialist',
    nationality_expertise: 'Italy',
    competition_expertise: 'Serie A',
    total_reports: 41,
    total_reports_norm: 0.78,
    total_reports_rank: 18,
    original_reports: 35,
    original_reports_norm: 0.76,
    original_reports_rank: 19,
    avg_potential: 7.9,
    avg_initial_age: 18.8,
    total_investment: 13500000,
    total_investment_rank: 12,
    net_profits: 6800000,
    net_profits_rank: 9,
    roi: 14.2,
    roi_norm: 0.72,
    roi_rank: 14,
    max_profit_report: 2100000,
    max_profit_report_rank: 8,
    min_profit_report: -120000,
    avg_profit_report: 165853,
    avg_profit_report_norm: 0.71,
    avg_profit_report_rank: 12,
    transfer_team_pts: 82.7,
    transfer_team_pts_norm: 0.79,
    transfer_team_pts_rank: 16,
    avg_initial_team_elo: 1680,
    avg_initial_team_level: 'Good',
    transfer_competition_pts: 90.5,
    transfer_competition_pts_norm: 0.87,
    transfer_competition_pts_rank: 8,
    avg_initial_competition_elo: 1780,
    avg_initial_competition_level: 'Very Good',
    scout_elo: 2050,
    scout_level: 'Excellent',
    scout_ranking: 12,
    join_date: new Date('2020-06-15')
  },
  {
    scout_name: 'Thomas Mueller',
    name: 'Thomas',
    surname: 'Mueller',
    date_of_birth: new Date('1990-09-03'),
    age: 33,
    nationality: 'Germany',
    email: 'thomas.mueller@scoutgermany.de',
    phone: '+49 176 12345678',
    city: 'Munich',
    country: 'Germany',
    favourite_club: 'Bayern Munich',
    open_to_work: true,
    professional_experience: 'Bundesliga talent scout with focus on youth development',
    nationality_expertise: 'Germany',
    competition_expertise: 'Bundesliga',
    total_reports: 29,
    total_reports_norm: 0.68,
    total_reports_rank: 28,
    original_reports: 24,
    original_reports_norm: 0.65,
    original_reports_rank: 30,
    avg_potential: 8.0,
    avg_initial_age: 17.5,
    total_investment: 7200000,
    total_investment_rank: 22,
    net_profits: 3600000,
    net_profits_rank: 18,
    roi: 11.8,
    roi_norm: 0.62,
    roi_rank: 22,
    max_profit_report: 1500000,
    max_profit_report_rank: 15,
    min_profit_report: -90000,
    avg_profit_report: 124137,
    avg_profit_report_norm: 0.64,
    avg_profit_report_rank: 20,
    transfer_team_pts: 86.3,
    transfer_team_pts_norm: 0.83,
    transfer_team_pts_rank: 11,
    avg_initial_team_elo: 1720,
    avg_initial_team_level: 'Very Good',
    transfer_competition_pts: 93.2,
    transfer_competition_pts_norm: 0.89,
    transfer_competition_pts_rank: 6,
    avg_initial_competition_elo: 1850,
    avg_initial_competition_level: 'Excellent',
    scout_elo: 1850,
    scout_level: 'Good',
    scout_ranking: 22,
    join_date: new Date('2022-01-08')
  },
  {
    scout_name: 'James Wilson',
    name: 'James',
    surname: 'Wilson',
    date_of_birth: new Date('1987-12-20'),
    age: 36,
    nationality: 'England',
    email: 'james.wilson@scoutengland.co.uk',
    phone: '+44 7700 123456',
    city: 'London',
    country: 'England',
    favourite_club: 'Chelsea FC',
    open_to_work: false,
    professional_experience: 'Premier League scout with Championship experience',
    nationality_expertise: 'England',
    competition_expertise: 'Premier League',
    total_reports: 53,
    total_reports_norm: 0.88,
    total_reports_rank: 8,
    original_reports: 47,
    original_reports_norm: 0.85,
    original_reports_rank: 9,
    avg_potential: 7.6,
    avg_initial_age: 19.0,
    total_investment: 18500000,
    total_investment_rank: 5,
    net_profits: 9200000,
    net_profits_rank: 5,
    roi: 16.8,
    roi_norm: 0.82,
    roi_rank: 7,
    max_profit_report: 2800000,
    max_profit_report_rank: 4,
    min_profit_report: -180000,
    avg_profit_report: 173584,
    avg_profit_report_norm: 0.76,
    avg_profit_report_rank: 9,
    transfer_team_pts: 89.1,
    transfer_team_pts_norm: 0.85,
    transfer_team_pts_rank: 9,
    avg_initial_team_elo: 1780,
    avg_initial_team_level: 'Very Good',
    transfer_competition_pts: 96.8,
    transfer_competition_pts_norm: 0.93,
    transfer_competition_pts_rank: 2,
    avg_initial_competition_elo: 1920,
    avg_initial_competition_level: 'Elite',
    scout_elo: 2280,
    scout_level: 'Elite',
    scout_ranking: 5,
    join_date: new Date('2019-11-12')
  }
]

async function createSampleScouts() {
  try {
    console.log('🚀 Creating sample scouts...')

    for (const scoutData of sampleScouts) {
      const scout = await prisma.scout.create({
        data: scoutData
      })
      console.log(`✅ Created scout: ${scout.scout_name} (${scout.nationality})`)
    }

    console.log(`🎉 Successfully created ${sampleScouts.length} sample scouts!`)

    // Mostrar estadísticas
    const totalScouts = await prisma.scout.count()
    console.log(`📊 Total scouts in database: ${totalScouts}`)

  } catch (_error) {
    console.error('❌ Error creating sample scouts:', error)
  } finally {
    await prisma.$disconnect()
  }
}

// Ejecutar si se llama directamente
if (require.main === module) {
  createSampleScouts()
}

export { createSampleScouts }