-- Tabla Atributos para almacenar todas las características detalladas de los jugadores
CREATE TABLE atributos (
    -- Identificadores y totales
    id_player INTEGER NOT NULL,
    id_fmi INTEGER,
    total_fmi_pts INTEGER,
    total_fmi_pts_norm INTEGER,
    
    -- Habilidades técnicas (jugador de campo)
    corners_fmi INTEGER,
    crossing_fmi INTEGER,
    dribbling_fmi INTEGER,
    finishing_fmi INTEGER,
    first_touch_fmi INTEGER,
    free_kick_taking_fmi INTEGER,
    heading_fmi INTEGER,
    long_shots_fmi INTEGER,
    passing_fmi INTEGER,
    penalty_taking_fmi INTEGER,
    tackling_fmi INTEGER,
    technique_fmi INTEGER,
    marking_fmi INTEGER,
    off_the_ball_fmi INTEGER,
    positioning_fmi INTEGER,
    long_throws_fmi INTEGER,
    
    -- Atributos físicos
    acceleration_fmi INTEGER,
    agility_fmi INTEGER,
    balance_fmi INTEGER,
    jumping_fmi INTEGER,
    natural_fitness_fmi INTEGER,
    pace_fmi INTEGER,
    stamina_fmi INTEGER,
    strength_fmi INTEGER,
    
    -- Atributos mentales
    aggression_fmi INTEGER,
    anticipation_fmi INTEGER,
    bravery_fmi INTEGER,
    composure_fmi INTEGER,
    concentration_fmi INTEGER,
    decisions_fmi INTEGER,
    determination_fmi INTEGER,
    flair_fmi INTEGER,
    leadership_fmi INTEGER,
    team_work_fmi INTEGER,
    vision_fmi INTEGER,
    work_rate_fmi INTEGER,
    
    -- Portero (GK)
    aerial_ability_fmi INTEGER,
    command_of_area_fmi INTEGER,
    communication_fmi INTEGER,
    eccentricity_fmi INTEGER,
    handling_fmi INTEGER,
    kicking_fmi INTEGER,
    one_on_ones_fmi INTEGER,
    tendency_to_punch_fmi INTEGER,
    reflexes_fmi INTEGER,
    rushing_out_fmi INTEGER,
    throwing_fmi INTEGER,
    
    -- Dominancia de pie
    left_foot_fmi INTEGER,
    right_foot_fmi INTEGER,
    
    -- Consistencia, personalidad y disponibilidad
    consistency_fmi INTEGER,
    dirtiness_fmi INTEGER,
    important_matches_fmi INTEGER,
    injury_proness_fmi INTEGER,
    versality_fmi INTEGER,
    adaptability_fmi INTEGER,
    ambition_fmi INTEGER,
    loyalty_fmi INTEGER,
    pressure_fmi INTEGER,
    professional_fmi INTEGER,
    sportsmanship_fmi INTEGER,
    temperament_fmi INTEGER,
    controversy_fmi INTEGER,
    
    -- Aptitud por posición (rating + nivel)
    goalkeeper_fmi INTEGER,
    gk_level INTEGER,
    defender_right_fmi INTEGER,
    rb_level INTEGER,
    defender_central_fmi INTEGER,
    cb_level INTEGER,
    defender_left_fmi INTEGER,
    lb_level INTEGER,
    wing_back_right_fmi INTEGER,
    rwb_level INTEGER,
    defensive_midfielder_fmi INTEGER,
    dm_level INTEGER,
    wing_back_left_fmi INTEGER,
    lwb_level INTEGER,
    midfielder_right_fmi INTEGER,
    rm_level INTEGER,
    midfielder_central_fmi INTEGER,
    cm_level INTEGER,
    midfielder_left_fmi INTEGER,
    lm_level INTEGER,
    attacking_mid_right_fmi INTEGER,
    rw_level INTEGER,
    attacking_mid_central_fmi INTEGER,
    am_level INTEGER,
    attacking_mid_left_fmi INTEGER,
    lw_level INTEGER,
    striker_fmi INTEGER,
    st_level INTEGER,
    
    -- Roles/estilos de Portero (con % de pertenencia)
    gk_dominator INTEGER,
    gk_dominator_percent INTEGER,
    gk_reactive INTEGER,
    gk_reactive_percent INTEGER,
    gk_initiator INTEGER,
    gk_initiator_percent INTEGER,
    
    -- Roles/estilos de Defensa Central (con %)
    central_def_aggressor INTEGER,
    central_def_aggressor_percent INTEGER,
    central_def_spreader INTEGER,
    central_def_spreader_percent INTEGER,
    central_def_anchor INTEGER,
    central_def_anchor_percent INTEGER,
    
    -- Roles/estilos de Defensa/Laterales (con %)
    wide_def_overlapper INTEGER,
    wide_def_overlapper_percent INTEGER,
    wide_def_progressor INTEGER,
    wide_def_progressor_percent INTEGER,
    wide_def_safety INTEGER,
    wide_def_safety_percent INTEGER,
    
    -- Mediocentro (con %)
    deep_mid_box_to_box INTEGER,
    deep_mid_box_to_box_percent INTEGER,
    deep_mid_distributor INTEGER,
    deep_mid_distributor_percent INTEGER,
    deep_mid_builder INTEGER,
    deep_mid_builder_percent INTEGER,
    
    -- Mediapunta/Interior avanzado (con %)
    advanced_mid_box_crasher INTEGER,
    advanced_mid_box_crasher_percent INTEGER,
    advanced_mid_creator INTEGER,
    advanced_mid_creator_percent INTEGER,
    advanced_mid_orchestrator INTEGER,
    advanced_mid_orchestrator_percent INTEGER,
    
    -- Extremos/ataque por banda (con %)
    wide_att_outlet INTEGER,
    wide_att_outlet_percent INTEGER,
    wide_att_unlocker INTEGER,
    wide_att_unlocker_percent INTEGER,
    wide_att_threat INTEGER,
    wide_att_threat_percent INTEGER,
    
    -- Delantero centro (con %)
    central_att_roamer INTEGER,
    central_att_roamer_percent INTEGER,
    central_att_target INTEGER,
    central_att_target_percent INTEGER,
    central_att_finisher INTEGER,
    central_att_finisher_percent INTEGER,
    
    -- Arquetipos físico-técnicos (índice + nivel)
    sprinter INTEGER,
    sprinter_level INTEGER,
    marathonian INTEGER,
    marathonian_level INTEGER,
    bomberman INTEGER,
    bomberman_level INTEGER,
    "360º" INTEGER,
    "360º_level" INTEGER,
    the_rock INTEGER,
    the_rock_level INTEGER,
    air_flyer INTEGER,
    air_flyer_level INTEGER,
    "1vs1_off" INTEGER,
    "1vs1_off_level" INTEGER,
    intelligence INTEGER,
    intelligence_level INTEGER,
    game_pace INTEGER,
    game_pace_level INTEGER,
    striking INTEGER,
    striking_level INTEGER,
    ball_control INTEGER,
    ball_control_level INTEGER,
    creativity INTEGER,
    creativity_level INTEGER,
    "1vs1_def" INTEGER,
    "1vs1_def_level" INTEGER,
    reliability INTEGER,
    reliability_level INTEGER,
    competitiveness INTEGER,
    competitiveness_level INTEGER,
    injury_resistance INTEGER,
    injury_resistance_level INTEGER,
    transition INTEGER,
    transition_level INTEGER,
    keeping_the_ball INTEGER,
    keeping_the_ball_level INTEGER,
    progression INTEGER,
    progression_level INTEGER,
    finishing_archetype INTEGER,
    finishing_level INTEGER,
    set_piece INTEGER,
    set_piece_level INTEGER,
    aerial_play INTEGER,
    aerial_play_level INTEGER,
    ball_recovery INTEGER,
    ball_recovery_level INTEGER,
    defensive_shape INTEGER,
    defensive_shape_level INTEGER,
    goal_saving INTEGER,
    goal_saving_level INTEGER,
    
    -- Tendencias y "dominance" táctico-estilístico
    -- Ataque
    positional_att_tendency INTEGER,
    positional_att_tendency_percent INTEGER,
    direct_att_tendency INTEGER,
    direct_att_tendency_percent INTEGER,
    positional_att_dominance INTEGER,
    positional_att_dominance_level INTEGER,
    direct_att_dominance INTEGER,
    direct_att_dominance_level INTEGER,
    
    -- Defensa (altura del bloque)
    low_block_def_tendency INTEGER,
    low_block_def_tendency_percent INTEGER,
    high_block_def_tendency INTEGER,
    high_block_def_tendency_percent INTEGER,
    low_block_def_dominance INTEGER,
    low_block_def_dominance_level INTEGER,
    high_block_def_dominance INTEGER,
    high_block_def_dominance_level INTEGER,
    
    -- Influencia por fase
    influence_off_tendency INTEGER,
    influence_off_tendency_percent INTEGER,
    influence_def_tendency INTEGER,
    influence_def_tendency_percent INTEGER,
    influence_off_dominance INTEGER,
    influence_off_dominance_level INTEGER,
    influence_def_dominance INTEGER,
    influence_def_dominance_level INTEGER,
    
    -- Espacios de juego
    open_spaces_tendency INTEGER,
    open_spaces_tendency_percent INTEGER,
    tight_spaces_tendency INTEGER,
    tight_spaces_tendency_percent INTEGER,
    open_spaces_dominance INTEGER,
    open_spaces_dominance_level INTEGER,
    tight_spaces_dominance INTEGER,
    tight_spaces_dominance_level INTEGER,
    
    -- Perfil de pie
    right_foot_tendency INTEGER,
    right_foot_tendency_percent INTEGER,
    left_foot_tendency INTEGER,
    left_foot_tendency_percent INTEGER,
    right_foot_dominance INTEGER,
    right_foot_dominance_level INTEGER,
    left_foot_dominance INTEGER,
    left_foot_dominance_level INTEGER,
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Índices y claves
    PRIMARY KEY (id_player),
    FOREIGN KEY (id_player) REFERENCES players(id) ON DELETE CASCADE,
    INDEX idx_id_fmi (id_fmi),
    INDEX idx_total_fmi_pts (total_fmi_pts),
    INDEX idx_sprinter_level (sprinter_level),
    INDEX idx_marathonian_level (marathonian_level),
    INDEX idx_bomberman_level (bomberman_level),
    INDEX idx_the_rock_level (the_rock_level),
    INDEX idx_air_flyer_level (air_flyer_level)
);

-- Comentarios para documentar la tabla
ALTER TABLE atributos COMMENT = 'Tabla de atributos detallados FMI para análisis avanzado de jugadores';

-- Comentarios para columnas clave
ALTER TABLE atributos 
MODIFY COLUMN id_player INTEGER NOT NULL COMMENT 'ID interno del jugador (FK a players)',
MODIFY COLUMN id_fmi INTEGER COMMENT 'ID en la fuente FMI',
MODIFY COLUMN total_fmi_pts INTEGER COMMENT 'Suma total de puntos FMI',
MODIFY COLUMN total_fmi_pts_norm INTEGER COMMENT 'Total normalizado para comparabilidad global';